export interface GetExistingTaskDetail {
    Code: number;
    TaskId: number;
    TaskCode: string;
    OPTM_USERID: string;
    OPTM_RESTYPE: string;
    OPTM_STATUS: string;
    StartDate: string;
    EndDate: string;
    TaskDuration: string;
    Description: string;
    ProducedQty: string;
    OPTM_QTYACCEPTED: number;
    RejectedQty: number;
    NCQty: number;
    OPTM_ABORTREASON: string;
    OPTM_POSTINGREADY: string;
    OPTM_POSTEDDATE: string;
    OPTM_POSTED: string;
    MoveOrder: string;
    OPTM_CREATEDATE: string;
    OPTM_BREAKTIME: number,
    OPTM_WORKTIME: number,
    OPTM_REMAININGQTY: number,
    OPTM_FROMOPRCODE: string;
    OPTM_FGCODE: string;
    OPTM_OPNSTDATETIME: string;
    OPTM_OPNENDDATETIME: string;
    OPTM_WONO: string;
    OPTM_WC: string
    OPTM_FROMOPERNO: number;
    OPTM_QTYTOPROD: number;
    OPTM_REASONTYPE: string;
    OPTM_DURATION: string;
    OPTM_INTRPTDATE: string;
    OPTM_RESUMEDATE: string;
    OPTM_REMARKS: string
    U_O_STARTDATE: string;
    U_O_ENDDATE: string;
    OpnStartPer: number;
    OpnEndPer: number;
    StdTime: number;
    AssignedQty: number;
    AssignedTime: number;
    FormattedAssiTime: string;
    FormattedOprStartPer: string;
    FormattedOprEndPer: string;
    FormattedStdTime: string;
}